main: io.github.kkauaon.Plugin
name: kCasas
description: Plugin de Casas
api-version: 1.16
version: 1.0.0
author: KKauaBR

commands:
   casas:
      description: Ver suas casas salvas
      permission: kcasas.ver
      usage: /<command>